### ISSUE TITLE
What's a StopException?

### ISSUE THREAD

**Issue by UnHumbleBen** [chipsalliance/treadle#203]
Most libraries have documentation. Is this library an exception? How come I can't find any description for the basic exception types such as StopException?

From the code [here](https://github.com/freechipsproject/treadle/blob/962acf6f7b5fbca3fe17ebe2897dcd48d6c465a1/src/main/scala/treadle/executable/TreadleException.scala)

**Comment by chick** [comment]
This library is typically run from within [ChiselTest](https://github.com/ucb-bar/chisel-testers2) or [chisel-iotesters](https://github.com/freechipsproject/chisel-testers) and is not directly seen by users. But there should be more documentation. The `StopException` is when a chisel stop directive's stop condition is met. And is caught by the simulation harness in order to report the event. In general the only other Exception thrown by this library is a TreadleException which indicates some sort of problem with the test code or harness, and in other cases indicates a probable bug in Treadle
