### ISSUE TITLE
Question: why treadle choose to work on FIRRTL rather than directly with the chisel generated DUT top?

### ISSUE THREAD

**Issue by yanghao** [chipsalliance/treadle#319]
With my very limited knowledge and understanding of how Chisel works, it constructs hardware blocks using Chisel libraries and native scala language (if/else, loops, etc). The *description* itself is not simulate-able, but the execution result of such a *description* is. Eventually, I think some kind of scala object representing all the interconnected hierarchical hardware is generated, and then that object is used to generate the FIRRTL representation.

Treadle (including chisel-tester) chooses to directly work with FIRRTL, wouldn't it easier if it chooses to work directly with that _object_? (if that object exists ...) Are there any difficulties doing so, or any particular consideration leads to the decision of parsing again FIRRTL?

Thanks.

**Comment by jackkoenig** [comment]
While it's true that there is a Scala object representation of the circuit in Chisel before FIRRTL, it's intended as an implementation detail rather than well-defined API. The purpose of FIRRTL is to be a well-defined intermediate representation for things like custom transformations and simulation. So to answer your question, FIRRTL is the intended API for such things as Treadle and chiseltest.
